#https://taskfile.dev/usage/
version: '3'

tasks:
  run:
    dir: '{{.USER_WORKING_DIR}}/cmd/server'
    cmds:
      - go run main.go
    env:
      CONFIG_PATH: '{{.USER_WORKING_DIR}}/config/config.toml'